# This is the docker compose file to start a mariaDB server image which will contain the database as defined in schema.sql
# Make sure to secure your database and choose the correct namings
# FULL CAPITALS means: fixed value, and you will need to change/add it.
version: '3'
volumes:
  data:
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: DATABASE_BLOK_2
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"